# Project config file

## 1. Upload clean data to directory clean_data/;
## 2. Manually modify each library name (e.g.: L1_1.fq.gz) or using rename regexp batch rename
#cd ~/ath/jt.terpene.16S/batch3
#mkdir clean_data
#ln /mnt/bai/yongxin/ath/jt.terpene.16S/clean_data/T*.gz clean_data/ -s
#rename 's/T\d\d/T/' clean_data/*
#ln /mnt/bai/yongxin/ath/jt.terpene.16S/170425-1/clean_data/*.gz clean_data/ -s
## 3. Upload mapping file, design, compare_group.txt and venn_group.txt according to each library to doc/
#mkdir doc
#ln /mnt/bai/yongxin/ath/jt.terpene.16S/doc/T*.txt doc/ -s
#rename 's/T\d\d/T/' doc/*
#ln /mnt/bai/yongxin/ath/jt.terpene.16S/170425-1/doc/L*.txt doc/ -s
#cat ../doc/design.txt <(tail -n+2 ../170425-1/doc/design.txt) > doc/design.txt
## 4. Manually set variable in the following part
## 5. Preparing files?

# Standard pipeline parameter
# working directory
wd=/mnt/bai/yongxin/ath/jt.terpene.16S/batch3
# library list
list=T1 T2 T3 T4 L1
rdp=/mnt/bai/public/ref/rdp_gold.fa # rdp gold database, for remove chimera
gg_align=/mnt/bai/public/ref/gg_13_8_otus/rep_set_aligned/97_otus.fasta # greengene bacterial 16S database
gg_seq=/mnt/bai/public/ref/gg_13_8_otus/rep_set/97_otus.fasta
gg_tax=/mnt/bai/public/ref/gg_13_8_otus/taxonomy/97_otu_taxonomy.txt
log=result/readme.log # log file for basic statistics
bc1=0 # forword barcode length, according to experiment design
bc2=6 # forword barcode length, according to experiment design
quality=19 # base quality, accurate > 99%; 29 means 99.9%
bt=6 # barcode type, usually length equal barcode 1 add barcode 2
primer5=AACMGGATTAGATACCCKG # 5` primer used for 16S
primer3=GGAAGGTGGGGATGACGT # 3` primer used for 16S, must reverse compliment
min_len=300 # min length, recommend 300 for bacterial 16S and 220 for ITS
thre_count=5000 # sample min count, filter samples less than thre_count
minuniquesize=2 # min count of unique reads
sim=0.97 # similarity of cluster OTU
p=32 # threads number used: 32
tax_per=0.005 # filter OTU percentage > 0.5% for draw taxonomy and phylogenetic tree, 0.1% about 150 OTU is too much to show
method=rdp # rdp, blast, rtax, mothur, uclust, sortmerna , default=uclust, recommend rdp is better
rarefaction=10000 # alpha rarefaction count, recoomend 1000, at least 5000
design=$(wd)/doc/design.txt # design file
result=result

# Deisgn subset
# if merge_group TRUE, group_order=FALSE
merge_group=FALSE
# if merge_group TRUE, group_order=FALSE
group_order=TRUE
# default compare group list in group_compare.txt
compare_group=$(wd)/doc/group_compare.txt
pair_compare=TRUE
g1=genotype
# cut -f 5 doc/design.txt |sort|uniq|awk '{print "\""$1"\""}'|tr "\n" ","
g1_list='"WT","DM1","DM2","DO1","DO2"'
g2=batch
g2_list='"3"'
tax_number=5
# figure size, recommend 4x2.5(default), 5x3, 8x5, 16x10
width=5 
height=3
# text_size default 8, alternative 7, 6
text_size=7
venn=$(wd)/doc/group_venn.txt

# OTU taxonomy and abundance filter parameter
thre=0.001 # threshold of filter low abundance OTU
taxonomy=p__Cyanobacteria,p__Chloroflexi # filter some phylum
# result based on filter OTU table
result_f=result_k1-c
otu_stat_style=percentage # add css or percentage mean add normlized value, default no sample data

init:
	touch $@
	mkdir -p clean_data
	mkdir -p doc
	mkdir -p temp
	mkdir -p result
	ls clean_data/*.gz|cut -f 2 -d '/'|cut -f 1 -d '_'|uniq>doc/library.txt
	


